export const RPGSystemsStats = [
  {
    title: "Dungeons & Dragons (5th edition)",
    values: [
      "Strength",
      "Dexterity",
      "Constitution",
      "Intelligence",
      "Wisdom",
      "Charisma"
    ]
  },
  {
    title: "Dungeons & Dragons - Expanded (5th edition)",
    values: [
      "Hit points",
      "Maximum hit points",
      "Temporary points",
      "Armor class",
      "Innitiative",
      "Piety",
      "Renown",
      "Proficiency bonus"
    ]
  },
  {
    title: "Dungeons & Dragons - Travel speeds (5th edition)",
    values: [
      "Movement speed",
      "Fly speed",
      "Swim speed",
      "Climb speed"
    ]
  },
  {
    title: "Dungeons & Dragons - Saving throws (5th edition)",
    values: [
      "Strength (saving)",
      "Dexterity (saving)",
      "Constitution (saving)",
      "Intelligence (saving)",
      "Wisdom (saving)",
      "Charisma (saving)"
    ]
  },
  {
    title: "Mass Effect (D20, 5e)",
    values: [
      "Strenght",
      "Dexterity",
      "Constitution",
      "Intelligence ",
      "Wisdom",
      "Charisma",
      "Defense (total)",
      "Defense (size) ",
      "Defense (cover) ",
      "Shield/Shields ",
      "Plating",
      "Reduction ",
      "Size",
      "Age ",
      "Level/Class Level ",
      "Paragon ",
      "Renegade ",
      "Power",
      "Biotics",
      "Biotic Points ",
      "Tech Points ",
      "Attack (bab/base Attack) ",
      "Rank ",
      "Ranks ",
      "Modifier",
      "Mod ",
      "Ability Modifier",
      "Misc Modifier ",
      "Bonus ",
      "Total Bonus",
      "Attack",
      "Attack Bonus ",
      "Action ",
      "Range",
      "Ammunition",
      "Damage ",
      "Critical ",
      "Recoil",
      "Armor ",
      "Armor Special Qualities ",
      "Head ",
      "Shoulders",
      "Arms",
      "Chest ",
      "Legs ",
      "Others ",
      "Cost",
      "Thermal Clips ",
      "Heat",
      "Medi-Gel",
      "Grenades",
      "Repair Kits",
      "Dc",
      "Maintenance ",
      "Cooldown",
      "Activation",
      "Load/Carry Capaccity (light) ",
      "Load/Carry Capaccity (medium) ",
      "Load/Carry Capaccity (heavy) ",
      "Amount ",
      "Credits"
    ]
  },
  {
    title: "Vampire: Masquerade (5th edition, World of Darkness)",
    values: [
      "Strength",
      "Dexterity",
      "Stamina",
      "Charisma",
      "Manipulation",
      "Composure",
      "Intelligence",
      "Wits",
      "Resolve",
      "Health",
      "Willpower",
      "Humanity"
    ]
  },
  {
    title: "Paranoia (Red Clearance)",
    values: [
      "Violence",
      "Brains",
      "Chutzpah",
      "Mechanics",
      "Athletics",
      "Guns",
      "Melee",
      "Throw",
      "Science",
      "Psychology",
      "Bureaucracy",
      "Alpha Complex",
      "Bluff",
      "Charm",
      "Intimdate",
      "Stealth",
      "Operate",
      "Engineer",
      "Program",
      "Demolitions"
    ]
  },
  {
    title: "Shadowrun (6th edition)",
    values: [
      "Body",
      "Agility",
      "Reaction",
      "Willpower",
      "Intuition",
      "Edge",
      "Essence",
      "Magic/Resonance",
      "Initiative (matrix)",
      "Initiative (astral)",
      "Composure",
      "Judge",
      "Intentions",
      "Memory",
      "Lift/Carry",
      "Movement",
      "Dam",
      "Damage",
      "Acc",
      "Accuracy",
      "Ap",
      "Action",
      "Points",
      "Rc",
      "Ammo",
      "Rating",
      "Rtg",
      "Nuyen",
      "Funds",
      "Currency"
    ]
  },
  {
    title: "Fading Suns",
    values: [
      "Body",
      "Strength",
      "Dexterity",
      "Endurance",
      "Mind",
      "Wits",
      "Perception",
      "Tech",
      "Spirit",
      "Vitality",
      "Wyrd",
      "Charm",
      "Dodge",
      "Fight",
      "Impress",
      "Melee",
      "Observe",
      "Shoot",
      "Sneak",
      "Vigor"
    ]
  },
  {
    title: "Cyberpunk (RED)",
    values: [
      "Intelligence",
      "Willpower",
      "Cool",
      "Empathy",
      "Technique",
      "Reflexes",
      "Luck",
      "Body",
      "Dexterity",
      "Movement"
    ]
  },
  {
    title: "Mutant: Year Zero",
    values: [
      "Strength",
      "Agility",
      "Wits",
      "Empathy",
      "Damage",
      "Fatigue",
      "Confusion",
      "Doubt"
    ]
  },
  {
    title: "GURPS (3rd & 4th edition)",
    values: [
      "Strength",
      "Agility",
      "Wits",
      "Empathy",
      "Damage",
      "Fatigue",
      "Confusion",
      "Doubt"
    ]
  },
  {
    title: "7th Sea (2nd edition)",
    values: [
      "Brawn",
      "Finesse",
      "Resolve",
      "Wits",
      "Panache"
    ]
  },
  {
    title: "7th Sea - Villain (2nd edition)",
    values: [
      "Strength",
      "Influence"
    ]
  },
  {
    title: "Apocalypse World (2nd edition, Powered by the Apocalypse)",
    values: [
      "Cool",
      "Hard",
      "Hot",
      "Sharp",
      "Weird",
      "HX"
    ]
  },
  {
    title: "Dresden Files RPG",
    values: [
      "Alertness",
      "Athletics",
      "Burglary",
      "Contacts",
      "Conviction",
      "Craftsmanship",
      "Deceit",
      "Discipline",
      "Driving",
      "Empathy",
      "Endurance",
      "Fists",
      "Guns",
      "Intimidation",
      "Investigation",
      "Lore",
      "Might",
      "Performance",
      "Presence",
      "Rapport",
      "Resources",
      "Scholarship",
      "Stealth",
      "Survival",
      "Weapons"
    ]
  },
  {
    title: "Traveller (2nd edition)",
    values: [
      "Strength",
      "Dexterity",
      "Endurace",
      "Intelligence",
      "Education",
      "Social",
      "Standing"
    ]
  },
  {
    title: "Cypher System",
    values: [
      "Intellect",
      "Might",
      "Speed"
    ]
  },
  {
    title: "Blades in the Dark",
    values: [
      "Attune",
      "Command",
      "Consort",
      "Finesse",
      "Hunt",
      "Prowl",
      "Skirmish",
      "Study",
      "Survey",
      "Sway",
      "Tinker",
      "Wreck",
      "Insight",
      "Prowess",
      "Tesolve"
    ]
  },
  {
    title: "World of Darkness ( 20th Anniversary Edition, Changeling the Dreaming)",
    values: [
      "Strength",
      "Dexterity",
      "Stamina",
      "Charisma",
      "Manipulation",
      "Appearance",
      "Perception",
      "Intelligence",
      "Wits",
      "Health (real)",
      "Health (chimerical)",
      "Glamour",
      "Willpower",
      "Nightmare",
      "Banality"
    ]
  },

  "Absorption",
  "Alertness",
  "Attack",
  "Avoidance",
  "Awareness",
  "Block",
  "Brawn",
  "Cautiousness",
  "Chance",
  "Damage",
  "Defense",
  "Deftness",
  "Dodge",
  "Ego",
  "Endurance",
  "Energy",
  "Evasion",
  "Fate",
  "Fatigue",
  "Finesse",
  "Fortitude",
  "Honor",
  "Hit Points (HP)",
  "Immunity",
  "Level",
  "Magic",
  "Mana",
  "Mana Points (MP)",
  "Might",
  "Mind",
  "Morale",
  "Parry",
  "Personality",
  "Precision",
  "Presence",
  "Psyche",
  "Quickness",
  "Rank",
  "Rate",
  "Recovery",
  "Reduction",
  "Reflexes",
  "Resistence",
  "Sanity",
  "Sense",
  "Soul",
  "Speed",
  "Spellpower",
  "Spirit",
  "Stamina",
  "Swiftness",
  "Tier",
  "Vitality",
  "Willpower",
  "Wits"
]
