export const RPGSystemsStats = [
  {
    title: "Dungeons & Dragons (5th edition)",
    values: [
      "Strength",
      "Dexterity",
      "Constitution",
      "Intelligence",
      "Wisdom",
      "Charisma"
    ]
  },
  {
    title: "Dungeons & Dragons - Expanded (5th edition)",
    values: [
      "Hit points",
      "Maximum hit points",
      "Temporary points",
      "Armor class",
      "Innitiative",
      "Piety",
      "Renown",
      "Proficiency bonus"
    ]
  },
  {
    title: "Dungeons & Dragons - Travel speeds (5th edition)",
    values: [
      "Movement speed",
      "Fly speed",
      "Swim speed",
      "Climb speed"
    ]
  },
  {
    title: "Dungeons & Dragons - Saving throws (5th edition)",
    values: [
      "Strength (saving)",
      "Dexterity (saving)",
      "Constitution (saving)",
      "Intelligence (saving)",
      "Wisdom (saving)",
      "Charisma (saving)"
    ]
  },
  {
    title: "Mass Effect (D20, 5e)",
    values: [
      "Strenght",
      "Dexterity",
      "Constitution",
      "Intelligence ",
      "Wisdom",
      "Charisma",
      "Defense (total)",
      "Defense (size) ",
      "Defense (cover) ",
      "Shield/Shields ",
      "Plating",
      "Reduction ",
      "Size",
      "Age ",
      "Level/Class Level ",
      "Paragon ",
      "Renegade ",
      "Power",
      "Biotics",
      "Biotic Points ",
      "Tech Points ",
      "Attack (bab/base Attack) ",
      "Rank ",
      "Ranks ",
      "Modifier",
      "Mod ",
      "Ability Modifier",
      "Misc Modifier ",
      "Bonus ",
      "Total Bonus",
      "Attack",
      "Attack Bonus ",
      "Action ",
      "Range",
      "Ammunition",
      "Damage ",
      "Critical ",
      "Recoil",
      "Armor ",
      "Armor Special Qualities ",
      "Head ",
      "Shoulders",
      "Arms",
      "Chest ",
      "Legs ",
      "Others ",
      "Cost",
      "Thermal Clips ",
      "Heat",
      "Medi-Gel",
      "Grenades",
      "Repair Kits",
      "Dc",
      "Maintenance ",
      "Cooldown",
      "Activation",
      "Load/Carry Capaccity (light) ",
      "Load/Carry Capaccity (medium) ",
      "Load/Carry Capaccity (heavy) ",
      "Amount ",
      "Credits"
    ]
  },
  {
    title: "Vampire: Masquerade (5th edition, World of Darkness)",
    values: [
      "Strength",
      "Dexterity",
      "Stamina",
      "Charisma",
      "Manipulation",
      "Composure",
      "Intelligence",
      "Wits",
      "Resolve",
      "Health",
      "Willpower",
      "Humanity"
    ]
  },
  {
    title: "Paranoia (Red Clearance)",
    values: [
      "Violence",
      "Brains",
      "Chutzpah",
      "Mechanics",
      "Athletics",
      "Guns",
      "Melee",
      "Throw",
      "Science",
      "Psychology",
      "Bureaucracy",
      "Alpha Complex",
      "Bluff",
      "Charm",
      "Intimdate",
      "Stealth",
      "Operate",
      "Engineer",
      "Program",
      "Demolitions"
    ]
  },
  {
    title: "Shadowrun (6th edition)",
    values: [
      "Body",
      "Agility",
      "Reaction",
      "Willpower",
      "Intuition",
      "Edge",
      "Essence",
      "Magic/Resonance",
      "Initiative (matrix)",
      "Initiative (astral)",
      "Composure",
      "Judge",
      "Intentions",
      "Memory",
      "Lift/Carry",
      "Movement",
      "Dam",
      "Damage",
      "Acc",
      "Accuracy",
      "Ap",
      "Action",
      "Points",
      "Rc",
      "Ammo",
      "Rating",
      "Rtg",
      "Nuyen",
      "Funds",
      "Currency"
    ]
  },
  {
    title: "Fading Suns",
    values: [
      "Body",
      "Strength",
      "Dexterity",
      "Endurance",
      "Mind",
      "Wits",
      "Perception",
      "Tech",
      "Spirit",
      "Vitality",
      "Wyrd",
      "Charm",
      "Dodge",
      "Fight",
      "Impress",
      "Melee",
      "Observe",
      "Shoot",
      "Sneak",
      "Vigor"
    ]
  },
  {
    title: "Cyberpunk (RED)",
    values: [
      "Intelligence",
      "Willpower",
      "Cool",
      "Empathy",
      "Technique",
      "Reflexes",
      "Luck",
      "Body",
      "Dexterity",
      "Movement"
    ]
  },
  {
    title: "Mutant: Year Zero",
    values: [
      "Strength",
      "Agility",
      "Wits",
      "Empathy",
      "Damage",
      "Fatigue",
      "Confusion",
      "Doubt"
    ]
  },
  {
    title: "GURPS (3rd & 4th edition)",
    values: [
      "Strength",
      "Dexterity",
      "Health",
      "Intelligence"
    ]
  },
  {
    title: "7th Sea (2nd edition)",
    values: [
      "Brawn",
      "Finesse",
      "Resolve",
      "Wits",
      "Panache"
    ]
  },
  {
    title: "7th Sea - Villain (2nd edition)",
    values: [
      "Strength",
      "Influence"
    ]
  },
  {
    title: "Apocalypse World (2nd edition, Powered by the Apocalypse)",
    values: [
      "Cool",
      "Hard",
      "Hot",
      "Sharp",
      "Weird",
      "HX"
    ]
  },
  {
    title: "Dresden Files RPG",
    values: [
      "Alertness",
      "Athletics",
      "Burglary",
      "Contacts",
      "Conviction",
      "Craftsmanship",
      "Deceit",
      "Discipline",
      "Driving",
      "Empathy",
      "Endurance",
      "Fists",
      "Guns",
      "Intimidation",
      "Investigation",
      "Lore",
      "Might",
      "Performance",
      "Presence",
      "Rapport",
      "Resources",
      "Scholarship",
      "Stealth",
      "Survival",
      "Weapons"
    ]
  },
  {
    title: "Traveller (2nd edition)",
    values: [
      "Strength",
      "Dexterity",
      "Endurace",
      "Intelligence",
      "Education",
      "Social",
      "Standing"
    ]
  },
  {
    title: "Cypher System",
    values: [
      "Intellect",
      "Might",
      "Speed"
    ]
  },
  {
    title: "Blades in the Dark",
    values: [
      "Attune",
      "Command",
      "Consort",
      "Finesse",
      "Hunt",
      "Prowl",
      "Skirmish",
      "Study",
      "Survey",
      "Sway",
      "Tinker",
      "Wreck",
      "Insight",
      "Prowess",
      "Tesolve"
    ]
  },
  {
    title: "World of Darkness ( 20th Anniversary Edition, Changeling the Dreaming)",
    values: [
      "Strength",
      "Dexterity",
      "Stamina",
      "Charisma",
      "Manipulation",
      "Appearance",
      "Perception",
      "Intelligence",
      "Wits",
      "Health (real)",
      "Health (chimerical)",
      "Glamour",
      "Willpower",
      "Nightmare",
      "Banality"
    ]
  },
  {
    title: "Microlite20 (expert rules)",
    values: [
      "Strength",
      "Dexterity",
      "Intellect",
      "Charisma",
      "Physical",
      "Knowledge",
      "Subterfuge",
      "Communication",
      "Survival",
      "Hit Points",
      "Armor Class"
    ]
  },
  {
    title: "Conspiracy X",
    values: [
      "Strength",
      "Size",
      "Agility",
      "Reflexes",
      "Intelligence",
      "Willpower",
      "Perception",
      "Good Luck",
      "Bad Luck",
      "Influence"
    ]
  },
  {
    title: "Call of Cthulu - Characteristics/Stats (7th edition)",
    values: [
      "Strength",
      "Constitution",
      "Power",
      "Dexterity",
      "Appearance",
      "Size",
      "Intelligence",
      "Education",
      "Movement Rate",
      "Hit Points",
      "Sanity",
      "Luck",
      "Magic Points",
      "Damage Bonus",
      "Build",
      "Dodge"
    ]
  },
  {
    title: "Call of Cthulu - Investigator Skills (7th edition)",
    values: [
      "Accounting",
      "Anthropology",
      "Appraise",
      "Archaeology",
      "Art/Craft",
      "Charm",
      "Climb",
      "Credit Rating",
      "Cthulu Mythos",
      "Disguise",
      "Dodge",
      "Drive Auto",
      "Electric Repair",
      "Fast Talk",
      "Fighting (brawl)",
      "Firearms (handgun)",
      "Firearms (rifle/shotgun)",
      "First Aid",
      "History",
      "Intimidate",
      "Jump",
      "Language (other)",
      "Language (own)",
      "Law",
      "Library Use",
      "Listen",
      "Locksmith",
      "Mechanical Repair",
      "Medicine",
      "Natural World",
      "Navigate",
      "Occult",
      "Operate Heavy",
      "Machine",
      "Persuade",
      "Pilot",
      "Psychology",
      "Psychoanalysis",
      "Ride",
      "Science",
      "Sleight of Hand",
      "Spot Hidden",
      "Stealth",
      "Survival",
      "Swim",
      "Throw",
      "Track"
    ]
  },
  {
    title: "Mork Borg",
    values: [
      "Melee",
      "Ranged",
      "Defence",
      "Agility - Defend",
      "Agility - Balance",
      "Agility - Swim",
      "Agility - Flee",
      "Presence - Perceive",
      "Presence - Aim",
      "Presence - Charm",
      "Presence - Wield Powers",
      "Strength - Crush",
      "Strength - Lift",
      "Strength - Strike",
      "Strength - Grapple",
      "Toughness - Resist Poison",
      "Toughness - Resist Cold",
      "Toughness - Resist Heat",
      "Toughness - Survive Falling"
    ]
  },
  {
    title: "Degenesis",
    values: [
      "Body",
      "Agility",
      "Charisma",
      "Intellect",
      "Psyche",
      "Instinct"
    ]
  },
  {
    title: "Feng Shui (1st edition)",
    values: [
      "Body (bod) - Move (mov)",
      "Body (bod) - Strength (str)",
      "Body (bod) - Constitution (con)",
      "Body (bod) - Toughness (tgh)",
      "Chi (chi) - Fortune (for)",
      "Chi (chi) - Kung Fu (fu)",
      "Chi (chi) - Magic (mag)",
      "Mind (mnd) - Charisma (Cha)",
      "Mind (mnd) - Intelligence (Int)",
      "Mind (mnd) - Perception (Per)",
      "Mind (mnd) - Willpower (Wil)",
      "Reflexes (ref) - Agility (agl)",
      "Reflexes (ref) - Dexterity (dex)",
      "Reflexes (ref) - Speed (spd)"
    ]
  },
  {
    title: "Fallout",
    values: [
      "Strength",
      "Perception",
      "Endurance",
      "Charisma",
      "Intelligence",
      "Agility",
      "Luck"
    ]
  },
  {
    title: "Star Trek Adventures - Personnel (Modiphius 2d20 System)",
    values: [
      "Control - Attribute",
      "Daring  - Attribute",
      "Fitness - Attribute",
      "Insight  - Attribute",
      "Presence - Attribute",
      "Reason - Attribute",
      "Command - Discipline",
      "Conn - Discipline",
      "Security - Discipline",
      "Engineering - Discipline",
      "Science - Discipline",
      "Medicine - Discipline"
    ]
  },
  {
    title: "Star Trek Adventures - Ships (Modiphius 2d20 System)",
    values: [
      "Engines - Systems",
      "Structure - Systems",
      "Computers - Systems",
      "Sensors - Systems",
      "Weapons - Systems",
      "Communications - Systems",
      "Command - Department",
      "Conn - Department",
      "Security - Department",
      "Engineering - Department",
      "Science - Department",
      "Medicine - Department"
    ]
  },
  {
    title: "Warhammer 40k (Dark Heresy 2)",
    values: [
      "Weapon Skill",
      "Ballistic Skill",
      "Strength",
      "Toughness",
      "Agility",
      "Intelligence",
      "Perception",
      "Willpower",
      "Fellowship",
      "Psy Rating",
      "Wounds",
      "Fatigue",
      "Insanity",
      "Corruption",
      "Influence",
      "Profit Factor",
      "Infamy"
    ]
  },

  "Absorption",
  "Alertness",
  "Attack",
  "Avoidance",
  "Awareness",
  "Block",
  "Brawn",
  "Cautiousness",
  "Chance",
  "Damage",
  "Defense",
  "Deftness",
  "Dodge",
  "Ego",
  "Endurance",
  "Energy",
  "Evasion",
  "Fate",
  "Fatigue",
  "Finesse",
  "Fortitude",
  "Honor",
  "Hit Points (HP)",
  "Immunity",
  "Level",
  "Magic",
  "Mana",
  "Mana Points (MP)",
  "Might",
  "Mind",
  "Morale",
  "Parry",
  "Personality",
  "Precision",
  "Presence",
  "Psyche",
  "Quickness",
  "Rank",
  "Rate",
  "Recovery",
  "Reduction",
  "Reflexes",
  "Resistence",
  "Sanity",
  "Sense",
  "Soul",
  "Speed",
  "Spellpower",
  "Spirit",
  "Stamina",
  "Swiftness",
  "Tier",
  "Vitality",
  "Willpower",
  "Wits"
]
